/**
 * Generated by orval v6.18.1 🍺
 * Do not edit manually.
 * Springdoc
 * Springdoc을 사용한 Swagger UI
 * OpenAPI spec version: 1.0.0
 */
import type { Authority } from "./authority";

export type AlarmAuthorityInsert1200 = {
  code?: string;
  data?: Authority;
  message?: string;
};
