/**
 * Generated by orval v6.18.1 🍺
 * Do not edit manually.
 * Springdoc
 * Springdoc을 사용한 Swagger UI
 * OpenAPI spec version: 1.0.0
 */

export interface AlarmEnabledRequest {
  /** 알람ID */
  alarmId?: number;
  /** 활성화여부(0:비활성화, 1:활성화) */
  enabled?: number;
}
