/**
 * Generated by orval v6.18.1 🍺
 * Do not edit manually.
 * Springdoc
 * Springdoc을 사용한 Swagger UI
 * OpenAPI spec version: 1.0.0
 */

export type AlarmAuthorityInsert1Params = {
  /**
   * 디바이스 ID
   */
  deviceId: string;
  /**
   * 알람권한 동의여부
   */
  authFlag: string;
};
