/**
 * Generated by orval v6.18.1 🍺
 * Do not edit manually.
 * Springdoc
 * Springdoc을 사용한 Swagger UI
 * OpenAPI spec version: 1.0.0
 */
import type { AlarmLocationTimeRequest } from "./alarmLocationTimeRequest";

/**
 * 알람지역목록
 */
export interface AlarmLocationRequest {
  /** 알람지역ID */
  alarmLocationId?: number;
  /** 법정동코드 */
  regionCd?: string;
  /** 시도 */
  cityDo?: string;
  /** 구군 */
  guGun?: string;
  /** 읍면동 */
  eupMyun?: string;
  /** 알람지역시간목록 */
  alarmLocationTimeRequest?: AlarmLocationTimeRequest[];
}
