/**
 * Generated by orval v6.18.1 🍺
 * Do not edit manually.
 * Springdoc
 * Springdoc을 사용한 Swagger UI
 * OpenAPI spec version: 1.0.0
 */

export interface AlarmSoundResponse {
  /** 알람소리ID */
  alarmSoundId?: number;
  /** 알람소리이름 */
  alarmSoundName?: string;
  /** 파일이름 */
  fileName?: string;
}
