/**
 * Generated by orval v6.18.1 🍺
 * Do not edit manually.
 * Springdoc
 * Springdoc을 사용한 Swagger UI
 * OpenAPI spec version: 1.0.0
 */

/**
 * 알람지역목록
 */
export interface AlarmLocationResponse {
  /** 시도 */
  cityDo?: string;
  /** 구군 */
  guGun?: string;
  /** 읍면동 */
  eupMyun?: string;
  /** AM, PM, ALL */
  timeOfDay?: string;
}
