/**
 * Generated by orval v6.18.1 🍺
 * Do not edit manually.
 * Springdoc
 * Springdoc을 사용한 Swagger UI
 * OpenAPI spec version: 1.0.0
 */

/**
 * 알람권한 VO
 */
export interface Authority {
  /** authority Id */
  authorityId?: number;
  /** 디바이스 ID */
  deviceId?: string;
  /** 알림권한 동의여부 */
  authFlag?: number;
  /** 알람권한 갱신일자 */
  authDate?: string;
}
