/**
 * Generated by orval v6.18.1 🍺
 * Do not edit manually.
 * Springdoc
 * Springdoc을 사용한 Swagger UI
 * OpenAPI spec version: 1.0.0
 */
import type { AlarmResponse } from "./alarmResponse";

export type GetAlarmList200 = {
  code?: string;
  data?: AlarmResponse[];
  message?: string;
};
