/**
 * Generated by orval v6.18.1 🍺
 * Do not edit manually.
 * Springdoc
 * Springdoc을 사용한 Swagger UI
 * OpenAPI spec version: 1.0.0
 */
import type { AlarmLocationWeatherDetailResponse } from "./alarmLocationWeatherDetailResponse";

export type GetAlarmLocationWeatherDetail200 = {
  code?: string;
  data?: AlarmLocationWeatherDetailResponse[];
  message?: string;
};
