/**
 * Generated by orval v6.18.1 🍺
 * Do not edit manually.
 * Springdoc
 * Springdoc을 사용한 Swagger UI
 * OpenAPI spec version: 1.0.0
 */

export type GetRecentLocationParams = {
  /**
   * userId
   */
  userId: string;
  /**
   * 시/도
   */
  cityDo: string;
  /**
   * 구/군
   */
  guGun: string;
  /**
   * 읍면동
   */
  eupMyun: string;
  /**
   * 법정동코드
   */
  regionCd: string;
};
