/**
 * Generated by orval v6.18.1 🍺
 * Do not edit manually.
 * Springdoc
 * Springdoc을 사용한 Swagger UI
 * OpenAPI spec version: 1.0.0
 */

export interface LocationResponse {
  시도명?: string;
  시군구명?: string;
  읍면동명?: string;
  행정구역코드?: string;
  위도?: string;
  경도?: string;
  X좌표?: string;
  Y좌표?: string;
}
