/**
 * Generated by orval v6.18.1 🍺
 * Do not edit manually.
 * Springdoc
 * Springdoc을 사용한 Swagger UI
 * OpenAPI spec version: 1.0.0
 */

export interface LocationResponse {
  /** 시도명) */
  cityDo?: string;
  /** 시군구명 */
  guGun?: string;
  /** 읍면동명 */
  eupMyun?: string;
  /** 행정구역코드 */
  regionCd?: string;
}
