/**
 * Generated by orval v6.18.1 🍺
 * Do not edit manually.
 * Springdoc
 * Springdoc을 사용한 Swagger UI
 * OpenAPI spec version: 1.0.0
 */

export type RefreshLocationForWeatherParams = {
  /**
   * 주소코드
   */
  regionCd: string;
  /**
   * 갱신타입(0:초단기예보, 1:단기예보)
   */
  refreshType: string;
};
