/**
 * Generated by orval v6.18.1 🍺
 * Do not edit manually.
 * Springdoc
 * Springdoc을 사용한 Swagger UI
 * OpenAPI spec version: 1.0.0
 */

export interface WeatherTestResponse {
  발표일자?: string;
  발표시각?: string;
  예보일자?: string;
  예보시각?: string;
  강수확률?: string;
  강수형태?: string;
  "1시간강수량"?: string;
  하늘상태?: string;
  "1시간기온"?: string;
  일최저기온?: string;
  일최기온?: string;
}
